! ============================================================================
! AtlasLab - lab 04-enterprise - core1 (AS 65100)
! ============================================================================
frr version 10.0
frr defaults traditional
hostname core1
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-core1
 ip address 10.4.255.11/32
!
interface eth1
 description LINK-TO-edge1-EDGE-CORE
 ip address 10.4.2.2/30
!
interface eth2
 description LINK-TO-edge2-EDGE-CORE
 ip address 10.4.2.10/30
!
interface eth3
 description LINK-TO-core2-CORE-CORE
 ip address 10.4.3.1/30
!
interface eth4
 description LINK-TO-dist1-CORE-DIST
 ip address 10.4.4.1/30
!
interface eth5
 description LINK-TO-dist2-CORE-DIST
 ip address 10.4.4.9/30
!
router ospf
 ospf router-id 10.4.255.11
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 no passive-interface eth3
 no passive-interface eth4
 no passive-interface eth5
 network 10.4.255.11/32 area 0.0.0.0
 network 10.4.2.0/30 area 0.0.0.0
 network 10.4.2.8/30 area 0.0.0.0
 network 10.4.3.0/30 area 0.0.0.0
 network 10.4.4.0/30 area 0.0.0.0
 network 10.4.4.8/30 area 0.0.0.0
exit
!
router bgp 65100
 no bgp ebgp-requires-policy
 no bgp network import-check
 bgp router-id 10.4.255.11
 neighbor 10.4.255.1 remote-as 65100
 neighbor 10.4.255.1 description IBGP-edge1
 neighbor 10.4.255.1 update-source lo
 neighbor 10.4.255.2 remote-as 65100
 neighbor 10.4.255.2 description IBGP-edge2
 neighbor 10.4.255.2 update-source lo
 neighbor 10.4.255.12 remote-as 65100
 neighbor 10.4.255.12 description IBGP-core2
 neighbor 10.4.255.12 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.4.255.1 next-hop-self
  neighbor 10.4.255.2 next-hop-self
  neighbor 10.4.255.12 next-hop-self
  maximum-paths ibgp 4
 exit-address-family
exit
!
line vty
!
