! ============================================================================
! AtlasLab - lab 02-ospf - r3
! ============================================================================
frr version 10.0
frr defaults traditional
hostname r3
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-r3
 ip address 10.2.255.3/32
!
interface eth1
 description LINK-TO-r2
 ip address 10.2.23.2/30
!
interface eth2
 description LINK-TO-r4
 ip address 10.2.34.1/30
!
interface eth3
 description LINK-TO-r1-DIAGONAL
 ip address 10.2.13.2/30
!
router ospf
 ospf router-id 10.2.255.3
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 no passive-interface eth3
 network 10.2.255.3/32 area 0.0.0.0
 network 10.2.23.0/30 area 0.0.0.0
 network 10.2.34.0/30 area 0.0.0.0
 network 10.2.13.0/30 area 0.0.0.0
exit
!
line vty
!
