! ============================================================================
! AtlasLab - lab 02-ospf - r2
! ============================================================================
frr version 10.0
frr defaults traditional
hostname r2
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-r2
 ip address 10.2.255.2/32
!
interface eth1
 description LINK-TO-r1
 ip address 10.2.12.2/30
!
interface eth2
 description LINK-TO-r3
 ip address 10.2.23.1/30
!
router ospf
 ospf router-id 10.2.255.2
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.2.255.2/32 area 0.0.0.0
 network 10.2.12.0/30 area 0.0.0.0
 network 10.2.23.0/30 area 0.0.0.0
exit
!
line vty
!
