! ============================================================================
! AtlasLab - lab 03-bgp - r1 (AS 65011)
! ============================================================================
frr version 10.0
frr defaults traditional
hostname r1
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-r1
 ip address 10.3.255.1/32
!
interface eth1
 description LINK-TO-r2-EBGP
 ip address 10.3.12.1/30
!
router bgp 65011
 no bgp ebgp-requires-policy
 no bgp network import-check
 bgp router-id 10.3.255.1
 neighbor 10.3.12.2 remote-as 65012
 neighbor 10.3.12.2 description EBGP-r2
 !
 address-family ipv4 unicast
  network 10.3.255.1/32
 exit-address-family
exit
!
line vty
!
