frr version 10.0
frr defaults traditional
hostname r2
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-r2
 ip address 10.1.255.2/32
!
interface eth1
 description LINK-TO-r1
 ip address 10.1.12.2/30
!
router ospf
 ospf router-id 10.1.255.2
 passive-interface default
 no passive-interface eth1
 network 10.1.255.2/32 area 0
 network 10.1.12.0/30 area 0
!
line vty
!
