! ============================================================================
! AtlasLab - lab 04-enterprise - dist1
! ============================================================================
frr version 10.0
frr defaults traditional
hostname dist1
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-dist1
 ip address 10.4.255.21/32
!
interface eth1
 description LINK-TO-core1-CORE-DIST
 ip address 10.4.4.2/30
!
interface eth2
 description LINK-TO-core2-CORE-DIST
 ip address 10.4.4.6/30
!
interface eth3
 description LINK-TO-access1-DIST-ACCESS
 ip address 10.4.5.1/30
!
interface eth4
 description LINK-TO-access2-DIST-ACCESS
 ip address 10.4.5.9/30
!
router ospf
 ospf router-id 10.4.255.21
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 no passive-interface eth3
 no passive-interface eth4
 network 10.4.255.21/32 area 0.0.0.0
 network 10.4.4.0/30 area 0.0.0.0
 network 10.4.4.4/30 area 0.0.0.0
 network 10.4.5.0/30 area 0.0.0.0
 network 10.4.5.8/30 area 0.0.0.0
exit
!
line vty
!
