#!/bin/sh
# AtlasLab - generated by scripts/generate-multicity.py - DO NOT EDIT BY HAND
# site=hyderabad
#
# Perimeter firewall for hyderabad: eth1 is the "outside" leg toward
# hyderabad-edge (the inter-city WAN), eth2 is the "inside" leg toward
# hyderabad-core (this site's internal network). Not a routing protocol
# speaker - see labs/07-multi-city/README.md for why the boundary here
# is deliberately static routes, not OSPF/BGP crossing the firewall.

# "replace", not "add", throughout this file: containerlab sets
# restart:always on every node, and if this script is ever interrupted
# partway through (or the container restarts for any other reason)
# after some of it already applied, a plain `ip addr add`/`ip route add`
# fails with "RTNETLINK answers: File exists" on the second run - which,
# combined with `set -e` in entrypoint.sh, crashes the container, which
# restarts it, which fails at the same spot again: an infinite crash
# loop that silently strands this node with no topology links at all
# (confirmed by direct testing - see docs/troubleshooting.md). `replace`
# is idempotent - it succeeds identically whether this is the first run
# or the fifth.
ip addr replace 10.90.2.2/30 dev eth1
ip link set eth1 up
ip addr replace 10.90.2.5/30 dev eth2
ip link set eth2 up

ip route replace default via 10.90.2.1 dev eth1
ip route replace 172.30.8.0/22 via 10.90.2.6 dev eth2
ip route replace 10.251.2.0/24 via 10.90.2.6 dev eth2

sysctl -w net.ipv4.ip_forward=1 >/dev/null

# --- Stateful policy -------------------------------------------------
# Flush first, same idempotency rationale as above - otherwise a rerun
# appends duplicate rules (harmless for correctness, but messy, and it
# masks the real problem if setup.sh legitimately runs more than once).
# Default-deny inbound from the WAN; the site's own outbound traffic is
# unrestricted. Only hyderabad-core and hyderabad-server are reachable from
# other cities (infrastructure + the one "published" node); the access
# tier (hyderabad-access1/hyderabad-access2) is deliberately internal-only -
# see labs/07-multi-city/expected-unreachable.txt, generated to match
# this exact policy.
iptables -F FORWARD
iptables -P FORWARD DROP
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i eth2 -o eth1 -j ACCEPT
iptables -A FORWARD -i eth1 -o eth2 -p icmp -d 10.251.2.2 -j ACCEPT
iptables -A FORWARD -i eth1 -o eth2 -p icmp -d 10.251.2.5 -j ACCEPT
iptables -A FORWARD -i eth1 -o eth2 -p tcp --dport 22 -d 10.251.2.5 -j ACCEPT
iptables -A FORWARD -i eth1 -o eth2 -j LOG --log-prefix "ATLASLAB-FW-HYDERABAD-DROP: " --log-level 4
