! ============================================================================
! AtlasLab - lab 04-enterprise - access2
! ============================================================================
frr version 10.0
frr defaults traditional
hostname access2
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-access2
 ip address 10.4.255.32/32
 ip address 172.16.211.1/24
!
interface eth1
 description LINK-TO-dist1-DIST-ACCESS
 ip address 10.4.5.10/30
!
interface eth2
 description LINK-TO-dist2-DIST-ACCESS
 ip address 10.4.5.14/30
!
router ospf
 ospf router-id 10.4.255.32
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.4.255.32/32 area 0.0.0.0
 network 172.16.211.0/24 area 0.0.0.0
 network 10.4.5.8/30 area 0.0.0.0
 network 10.4.5.12/30 area 0.0.0.0
exit
!
line vty
!
