! ============================================================================
! AtlasLab - lab 02-ospf - r4
! ============================================================================
frr version 10.0
frr defaults traditional
hostname r4
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-r4
 ip address 10.2.255.4/32
!
interface eth1
 description LINK-TO-r3
 ip address 10.2.34.2/30
!
interface eth2
 description LINK-TO-r1
 ip address 10.2.41.1/30
!
router ospf
 ospf router-id 10.2.255.4
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.2.255.4/32 area 0.0.0.0
 network 10.2.34.0/30 area 0.0.0.0
 network 10.2.41.0/30 area 0.0.0.0
exit
!
line vty
!
