! ============================================================================
! AtlasLab - lab 03-bgp - r3 (AS 65013)
! ============================================================================
frr version 10.0
frr defaults traditional
hostname r3
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-r3
 ip address 10.3.255.3/32
!
interface eth1
 description LINK-TO-r2-EBGP
 ip address 10.3.23.2/30
!
router bgp 65013
 no bgp ebgp-requires-policy
 no bgp network import-check
 bgp router-id 10.3.255.3
 neighbor 10.3.23.1 remote-as 65012
 neighbor 10.3.23.1 description EBGP-r2
 !
 address-family ipv4 unicast
  network 10.3.255.3/32
 exit-address-family
exit
!
line vty
!
