! ============================================================================
! AtlasLab - lab 04-enterprise - edge2 (AS 65100)
! ============================================================================
frr version 10.0
frr defaults traditional
hostname edge2
log file /var/log/frr/frr.log informational
log timestamp precision 3
service integrated-vtysh-config
!
interface lo
 description LOOPBACK-edge2
 ip address 10.4.255.2/32
!
interface eth1
 description LINK-TO-isp1-ISP-EDGE
 ip address 192.0.2.70/30
!
interface eth2
 description LINK-TO-edge1-EDGE-EDGE
 ip address 10.4.1.2/30
!
interface eth3
 description LINK-TO-core1-EDGE-CORE
 ip address 10.4.2.9/30
!
interface eth4
 description LINK-TO-core2-EDGE-CORE
 ip address 10.4.2.13/30
!
router ospf
 ospf router-id 10.4.255.2
 passive-interface default
 no passive-interface eth2
 no passive-interface eth3
 no passive-interface eth4
 network 10.4.255.2/32 area 0.0.0.0
 network 10.4.1.0/30 area 0.0.0.0
 network 10.4.2.8/30 area 0.0.0.0
 network 10.4.2.12/30 area 0.0.0.0
 redistribute bgp
exit
!
route-map RM-OSPF-TO-BGP permit 10
 match route-type internal
exit
!
ip prefix-list PL-ATLAS-LOOPBACKS seq 5 permit 10.4.255.0/24 le 32
ip prefix-list PL-ATLAS-LANS seq 5 permit 172.16.208.0/21 le 24
!
route-map RM-TO-ISP permit 10
 match ip address prefix-list PL-ATLAS-LOOPBACKS
exit
!
route-map RM-TO-ISP permit 20
 match ip address prefix-list PL-ATLAS-LANS
exit
!
router bgp 65100
 no bgp ebgp-requires-policy
 no bgp network import-check
 bgp router-id 10.4.255.2
 neighbor 10.4.255.1 remote-as 65100
 neighbor 10.4.255.1 description IBGP-edge1
 neighbor 10.4.255.1 update-source lo
 neighbor 10.4.255.11 remote-as 65100
 neighbor 10.4.255.11 description IBGP-core1
 neighbor 10.4.255.11 update-source lo
 neighbor 10.4.255.12 remote-as 65100
 neighbor 10.4.255.12 description IBGP-core2
 neighbor 10.4.255.12 update-source lo
 neighbor 192.0.2.69 remote-as 64600
 neighbor 192.0.2.69 description EBGP-isp1
 !
 address-family ipv4 unicast
  neighbor 10.4.255.1 next-hop-self
  neighbor 10.4.255.11 next-hop-self
  neighbor 10.4.255.12 next-hop-self
  maximum-paths ibgp 4
  redistribute ospf route-map RM-OSPF-TO-BGP
  neighbor 192.0.2.69 route-map RM-TO-ISP out
 exit-address-family
exit
!
line vty
!
